service: portfolio-slack-app
custom:
  # Log all events to CloudWatch
  slack_enable_logging: true
provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  memorySize: 128
  timeout: 4
  environment:
    GITHUB_API_KEY: ${env:GITHUB_API_KEY}
    SLACK_VERIFICATION_TOKEN: ${env:SLACK_VERIFICATION_TOKEN}
    SLACK_ACCESS_TOKEN: ${env:SLACK_ACCESS_TOKEN}

functions:
  hello:
    handler: handler.hello
  portfolioSlackApp:
    name: portfolio-slack-app
    description: Interact with dukelearninginnovation/portfolio
    handler: handler.portfolio
    events:
      - http:
          path: portfolio-slack-app
          method: post
          integration: lambda
          response:
            template: $input.path('$')